### ISSUE TITLE
Support multi-value declarations

### ISSUE THREAD

**Issue by hamlim** [hamlim/postcss-plugin-initial#2]
Example:

```css
p {
  background-repeat: initial no-repeat;
}
// out
p {
  background-repeat: repeat no-repeat;
}
```
