### ISSUE TITLE
Support all: initial

### ISSUE THREAD

**Issue by hamlim** [hamlim/postcss-plugin-initial#3]
This would involve running through the entire list from `css-initials` and printing them all out as a replacement.

```css
.class {
  all: initial;
}
```
